AWSTemplateFormatVersion: "2010-09-09"
Description: Yet Analytics SQL LRS DB init function hosting template. This template is provided for documentation purposes only. You do not need to run it to run SQL LRS.

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub Organization Name
    Default: yetanalytics
  RepositoryName:
    Type: String
    Description: GitHub Repository Name
    Default: lrsql
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider.
    Default: ""
    Type: String
  BucketName:
    Description: Name of the S3 bucket to create.
    Type: String
    Default: lrsql-db-initfn

Resources:
  HostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  HostingBucketPublicReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref HostingBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Resource:
              - !Sub "${HostingBucket.Arn}/*"
            Principal: "*"

  BucketWritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Description: IAM Policy to allow write to the SQL LRS DB Init Function hosting bucket
    Properties:
      ManagedPolicyName: !Sub "${AWS::StackName}-${AWS::Region}-lrsql-dbfn-bucket-write-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:PutObject"
            Resource:
              - !Sub "${HostingBucket.Arn}/*"

  BucketWriteRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref OIDCProviderArn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*
      ManagedPolicyArns:
        - !Ref BucketWritePolicy

Outputs:
  BucketWriteRoleArn:
    Value: !GetAtt BucketWriteRole.Arn
