name: CD

on: # TODO: tags
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@3.5
      with:
        cli: 1.10.3.943
    
    - name: Build Bundle
      run: make bundle

    - name: Compress Bundle
      run: | # Need to cd so that the zip file doesn't contain the parent dirs
        cd target/bundle
        zip -r ../../lrsql-${{ github.sha }}.zip ./

    - name: Archive Bundle
      uses: actions/upload-artifact@v2
      with:
        name: SQL LRS bundle
        path: lrsql-${{ github.sha }}.zip
