name: CI

on: push

jobs:
  nvd_scan:
    uses: yetanalytics/actions/.github/workflows/nvd-scan.yml@v0.0.4
    with:
      nvd-clojure-version: '2.9.0'
      classpath-command: 'clojure -Spath -A:db-h2:db-sqlite:db-postgres'
      nvd-config-filename: '.nvd/config.json'

  lint:
    uses: yetanalytics/workflow-linter/.github/workflows/linter.yml@872eb78c06d66eb108d081cd0092d0b64f9761b5
    with: 'src/bench src/build src/db src/main src/test'

  test:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        target: [test-h2, test-sqlite, test-postgres]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup CI Environment
      uses: yetanalytics/actions/setup-env@v0.0.4

    - name: Run Makefile Target ${{ matrix.target }}
      run: make ${{ matrix.target }}
