name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        target: [test-h2, test-sqlite, test-postgres]

    steps:
    - name: Setup CI Environment
      uses: yetanalytics/actions/setup-env@v0

    - name: Run Makefile Target ${{ matrix.target }}
      run: make ${{ matrix.target }}
