name: CI

on: push

jobs:
  nvd_scan:
    uses: yetanalytics/actions/.github/workflows/nvd-scan.yml@v0.0.2
    with:
      nvd-clojure-version: '2.0.0'
      classpath-command: 'clojure -Spath -A:db-h2:db-sqlite:db-postgres'
  
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Setup clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2022.03.04'

    - name: Setup CI Environment
      uses: yetanalytics/actions/setup-env@v0
    
    - name: Run clj-kondo linting
      run: clj-kondo --lint src/bench src/build src/db src/main src/test

  test:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        target: [test-h2, test-sqlite, test-postgres]

    steps:
    - name: Setup CI Environment
      uses: yetanalytics/actions/setup-env@v0

    - name: Run Makefile Target ${{ matrix.target }}
      run: make ${{ matrix.target }}
